---
resource_pools:
  - name: web
    network: concourse
    stemcell: (( grab meta.stemcell ))
    cloud_properties:
      instance_type: m3.medium

  - name: discovery
    network: concourse
    stemcell: (( grab meta.stemcell ))
    cloud_properties:
      instance_type: m3.medium

  - name: db
    network: concourse
    stemcell: (( grab meta.stemcell ))
    cloud_properties:
      instance_type: m3.medium

  - name: workers
    network: concourse
    stemcell: (( grab meta.stemcell ))
    cloud_properties:
      instance_type: m4.large

  - name: haproxy
    network: concourse
    stemcell: (( grab meta.stemcell ))
    cloud_properties:
      instance_type: m4.large

compilation:
  workers: 3
  network: concourse
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: c4.large

jobs:
  - name: haproxy
    resource_pool: haproxy
  - name: discovery
    resource_pool: discovery
  - name: web
    resource_pool: web
  - name: db
    resource_pool: db
  - name: worker
    resource_pool: workers
