---
networks:
- name: concourse
  type: manual
  subnets:
  - range: 10.244.18.0/24
    gateway: 10.244.18.1
    static:
    - 10.244.18.2 - 10.244.18.60

jobs:
- name: web
  networks:
  - name: concourse
    static_ips: (( static_ips 0, 1, 2, 3, 5 ))
- name: haproxy
  networks:
  - name: concourse
    static_ips: (( static_ips 10, 11, 12, 13, 14 ))
- name: worker
  networks:
  - name: concourse
- name: db
  networks:
  - name: concourse
